// playgrounds/inertia-vue/inertia/pages/posts/create.vue
<script setup lang="ts">
import { Head } from '@inertiajs/vue3'
import { Link } from '@tuyau/inertia/vue'

defineProps<{ version: number }>()
</script>

<template>
  <Head title="Homepage" />

  <div class="container">
    <div class="title">AdonisJS {{ version }} x Inertia x Vue.js</div>

    <Link route="home" :params="[]"> Go to Home </Link>
    <span>
      Learn more about AdonisJS and Inertia.js by visiting the
      <a href="https://docs.adonisjs.com/guides/inertia">AdonisJS documentation</a>.
    </span>
  </div>
</template>

// playgrounds/inertia-react/inertia/pages/posts/create.tsx
import { Head } from '@inertiajs/react'
import { Link } from '@tuyau/inertia/react'

export default function Home() {
  return (
    <>
      <Head title="Create post" />

      <div className="container">
        <p>Create post</p>
        <Link route="home" params={[]}></Link>
      </div>
    </>
  )
}
